### ISSUE TITLE
Checklist of features

### ISSUE THREAD

**Issue by quartzquark** [Arsukeey/chess#1]
- [ ] Organize code and make it more readable

- [x] Add castling

- [x] Add pawn promoting

- [x] Add en passant

- [ ] Show possible squares the selected piece can move to

- [x] Make king's square red when it is on check

- [x] Make `draw_error()` work as expected

- [ ] Make AI able to analyze end-game better

- [x] Add stalemate/draw/checkmate handling
